spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://localhost:9000
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.itheima.pojo

itcast: itheima

context:
  initializer:
    classes: com.itheima.event.MyApplicationContextInitializer
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
